### ISSUE TITLE
Converter o código de C++ para Rcpp

### ISSUE THREAD

**Issue by PedroBSB** [lamfo-unb/Options_Port_SPG#1]
@BEAVEES poderia botar o código em C++ que eu devo converter ?

**Comment by PedroBSB** [comment]
@BEAVEES o método que o cpp utiliza é a aproximação de Barone-Adesi Whaley. O pacote fOptions tem a função BAWAmericanApproxOption que calcula usando essa aproximação. Eu coloquei um exemplo na pasta test o nome do arquivo é **fOptions Example.R**

**Comment by PedroAMBH** [comment]
@PedroBSB , eu tinha testado e estava usadno esse pacote. Mas é o qeu eu disse que os numeros nao parecem ser muito bons. E ele não calcula as gregas que eu precisava. Muitas vezes ele não econtra solução.

**Comment by PedroBSB** [comment]
@PedroAMBH reabri o issue e vou fazer a conversão.
