### ISSUE TITLE
Nova busca - Não fechado por conter dados importantes.

### ISSUE THREAD

**Issue by PedroAMBH** [lamfo-unb/Options_Port_SPG#2]
Apos ajuste de parametros, a os resultados da maquina nao foram satisfatorios. Precisamos encontrar uma nova aboragem, procurar qualquer relacao entre machine learning e opcoes:
- SVM
- Neural Network

**Comment by PedroAMBH** [comment]
Nova abordagem foi econtraada.
O trabalho é a criacao de uma maquina que desenvolve as proprioas testrategias de formaçao de portfolio com opçoes.  Por meio do uso de RL.

**Comment by fernandaamorim** [comment]
http://www.sciencedirect.com/science/article/pii/S0957417414000566 olha ai @PedroAMBH

**Comment by fernandaamorim** [comment]
http://www.iaeng.org/publication/IMECS2015/IMECS2015_pp57-62.pdf 
https://www.ripublication.com/ijaer16/ijaerv11n5_36.pdf 
@PedroAMBH dá uma olhada nesses dois artigos sobre option pricing
