### ISSUE TITLE
Options as a Game: A RL problem - 03/02/2018

### ISSUE THREAD

**Issue by PedroAMBH** [lamfo-unb/Options_Port_SPG#4]
O objetivo deste trabalho é aplicar a sistemática de RL para criação de portfolios e aplicar para a criação de portfólios de opções. Dado que as gregas e as sistemáticas de opções permitem o cancelamento de risco e criação de renda fixas sintéticas, a variedade de tipos de retornos criados pela combinação dela, com diferentes riscos e retornos é infinita. 

Dados: temos 2 opções.
        Gerar uma base de dados de opções inventadas por nós, com dados de mercado. Neste caso não temos o comportamento do mercado. Mas podemos gerar quantos dados forem necessários a partir dos modelos de precificam.
        Usar dados de mercado. Captura de dados de preções e estatísticas de preções das opções de ações e comodistas. A limitação é não ter acesso a opções que já venceram.
Mais interessante é o segundo cenário pois avaliamos aplicação no mercado real. 

Material a ser lido:
Opções: Artigos relacionados a precificação, e utilidade no mercado.
ML em Finanças:
RL em Finanças: 
RL pra jogos: Q-learning.

https://classroom.udacity.com/courses/ud600/lessons/4100878601/concepts/6512308670923
https://link.springer.com/article/10.1007/s10472-006-9036-z

Mais importante:
https://arxiv.org/pdf/1706.10059.pdf

@Cayan-Portela , Por favor de uma olhada nesse ultimo artigo. E em RL pra finanças. 
@fernandaamorim , Da uma procurada nesses temas mencionados. 

Se não tiver problema pra vocês gostaria de juntarmos no inicio de janeiro para conversar sobre a abordagem. Ja tendo estudado um pouco sobre essas ideias.

**Comment by PedroBSB** [comment]
@PedroAMBH li o texto https://arxiv.org/pdf/1706.10059.pdf . Basicamente o que eles fizeram foi usar uma Deep Learning com Aprendizado por Reforço (Silver et. al. 2014, Lillicrap et. al. 2016) considerando custos de transação no Mercado de Criptomoedas (@JuliaAkaishi veja se podemos usar esse artigo no referencial do BubbleBitcoin. Vamos aproveitar muito do referencial anterior mas temos que atualizar com novos textos também). Então @PedroAMBH acho que basta termos um algoritmo legal de RL que a estrutura de aprendizado vai ser fácil.

**Comment by PedroBSB** [comment]
Podemos usar as bibliotecas https://cran.r-project.org/web/packages/ReinforcementLearning/index.html e https://cran.r-project.org/web/packages/gym/index.html para treinar as máquinas de RL. Um exercício legal para o @fernandaamorim e @Cayan-Portela é fazer alguns exemplos usando esses pacotes para dados arbitrários. Assim, podemos ver como funciona.
