### ISSUE TITLE
Replicar exemplo de RL - 10/03/2018

### ISSUE THREAD

**Issue by PedroAMBH** [lamfo-unb/Options_Port_SPG#7]
@jadermcs vou colocar aqui alguns exemplos de RL, que você pode replicar : 

- Este replica a expriencia do AlphaGO para outro jogo. Acho que é um bom exemplo do que vamos tentar fazer:  https://github.com/bhansconnect/alpha_zero_othello

-Esse é uma aplicão mais simples: 
https://github.com/farizrahman4u/qlearning4k
https://github.com/matthiasplappert/keras-rl

- Este artigo esta mais relacionado ao que queremos fazer (Ainda não achei exemplos disso):
 https://arxiv.org/pdf/1706.10059.pdf

@Cayan-Portela , da uma olhada no nesse gith e ve o que podemos aproveitar do que tem em R.
https://github.com/ludmattos/qLearningFinance

**Comment by jadermcs** [comment]
https://deeplearning4j.org/deepreinforcementlearning se tempo for importante...
